# Generated by Django 4.2.7 on 2025-08-12 19:45

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("director", "Руководитель"),
                            ("teacher", "Преподаватель"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("classrooms_count", models.PositiveIntegerField()),
                ("available_patterns", models.JSONField(default=list)),
                ("opening_time", models.TimeField(default="11:00")),
                ("closing_time", models.TimeField(default="18:00")),
                ("peak_start", models.TimeField(default="13:00")),
                ("peak_end", models.TimeField(default="17:00")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("equipment", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="learning_center.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
                "unique_together": {("branch", "number")},
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("elementary", "Elementary"),
                            ("pre_intermediate", "Pre-Intermediate"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper-Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schedule_pattern",
                    models.CharField(
                        choices=[
                            ("tue_thu", "Вторник + Четверг"),
                            ("wed_sat", "Среда + Суббота"),
                            ("mon_fri", "Понедельник + Пятница"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lesson_time", models.TimeField()),
                (
                    "lesson_duration",
                    models.DurationField(default=datetime.timedelta(seconds=2700)),
                ),
                ("max_students", models.PositiveIntegerField(default=8)),
                ("is_active", models.BooleanField(default=True)),
                ("current_unit", models.PositiveIntegerField(default=1)),
                ("lessons_in_current_unit", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="learning_center.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("regular", "Обычное занятие"),
                            ("control", "Контрольное занятие"),
                            ("vocabulary", "Расширенная лексика"),
                            ("makeup", "Отработка"),
                            ("trial", "Пробное занятие"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланировано"),
                            ("completed", "Проведено"),
                            ("cancelled", "Отменено"),
                            ("rescheduled", "Перенесено"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("attendance_count", models.PositiveIntegerField(default=0)),
                ("homework_assigned", models.TextField(blank=True)),
                ("lesson_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning_center.classroom",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning_center.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятия",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("parent_contact", models.CharField(blank=True, max_length=15)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("elementary", "Elementary"),
                            ("pre_intermediate", "Pre-Intermediate"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper-Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("paused", "Приостановлен"),
                            ("finished", "Завершил обучение"),
                            ("dropped", "Отчислен"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("planned_end_date", models.DateField()),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("in_progress", "В процессе"),
                            ("lessons_completed", "Основные занятия завершены"),
                            ("completed", "Полностью завершен"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("control_lesson_scheduled", models.BooleanField(default=False)),
                ("vocabulary_lesson_scheduled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="learning_center.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Юнит",
                "verbose_name_plural": "Юниты",
                "unique_together": {("group", "unit_number")},
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_role",
                    models.CharField(
                        choices=[
                            ("regular", "Обычный преподаватель"),
                            ("admin", "Администратор"),
                            ("director", "Руководитель"),
                            ("specialist", "Специалист"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("max_daily_load", models.PositiveIntegerField(default=8)),
                ("min_weekly_load", models.PositiveIntegerField(default=0)),
                ("preferred_load", models.PositiveIntegerField(default=20)),
                ("available_weekdays", models.JSONField(default=list)),
                ("can_teach_control_lessons", models.BooleanField(default=False)),
                ("can_teach_vocabulary_lessons", models.BooleanField(default=False)),
                ("is_director", models.BooleanField(default=False)),
                ("is_admin_teacher", models.BooleanField(default=False)),
                (
                    "base_rate_per_lesson",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "special_lesson_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "compensation_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "available_branches",
                    models.ManyToManyField(
                        related_name="teachers", to="learning_center.branch"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
            },
        ),
        migrations.CreateModel(
            name="ScheduleConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("teacher_double_booking", "Преподаватель в двух местах"),
                            ("classroom_double_booking", "Кабинет занят"),
                            ("teacher_overload", "Превышение дневной нагрузки"),
                            ("schedule_pattern_violation", "Нарушение паттерна группы"),
                            (
                                "branch_restriction",
                                "Недоступный филиал для преподавателя",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает решения"),
                            ("resolved", "Решено"),
                            ("ignored", "Проигнорировано"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning_center.classroom",
                    ),
                ),
                (
                    "lesson1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_lesson1",
                        to="learning_center.lesson",
                    ),
                ),
                (
                    "lesson2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_lesson2",
                        to="learning_center.lesson",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning_center.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфликт расписания",
                "verbose_name_plural": "Конфликты расписания",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="learning_center.teacher",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="learning_center.unit",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="main_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_groups",
                to="learning_center.teacher",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="learning_center.student"
            ),
        ),
        migrations.CreateModel(
            name="CompensationWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("substitution", "Замещение коллеги"),
                            ("individual", "Индивидуальное занятие"),
                            ("conversation_club", "Разговорный клуб"),
                            ("homework_check", "Проверка домашних заданий"),
                            ("parent_calls", "Обзвон родителей"),
                            ("materials_prep", "Подготовка материалов"),
                            ("debtor_work", "Работа с задолжниками"),
                            ("administrative", "Административная работа"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("scheduled_datetime", models.DateTimeField()),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=2700)),
                ),
                ("rate_per_hour", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_payment", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replaced_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning_center.lesson",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_work",
                        to="learning_center.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компенсационная работа",
                "verbose_name_plural": "Компенсационная работа",
            },
        ),
    ]
